version: '3'
services:
    capture_rabbitmq:
      image: rabbitmq:3
      hostname: capture_rabbitmq
      ports:
        - 25672:5672
      restart: always

    capture_worker:
      build:
        context: "../../"
        dockerfile: "docker/satellite/Dockerfile-downloader"
        args:
          PYTHON_VERSION: ${PYTHON_VERSION:-3.7}
      env_file:
        - .env
      environment:
        - CELERY_BROKER_URL=amqp://guest:guest@capture_rabbitmq:5672
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}
        - PSQL_PORT=${PSQL_PORT}
        - PSQL_HOST=${PSQL_HOST}
      volumes:
        - ../../:/AlertaDengueCaptura
      depends_on:
        - capture_rabbitmq
      restart: always

